---
date: "2025-01-30"
output: html_document
---

## Introduction

Since the turn of the century high pathogenicity avian influenza (HPAI) viruses, have increasingly emerged along with the increase in global poultry production. This causes a major burden to the poultry industry, and more recently also wild birds, livestock and humans. The goose/guandong lineage HPAI H5N1 virus emerged in 1996 and has been circulating and evolving further for decades, current descendants of the virus belonging to clade 2.3.4.4b causing a global panzootic. Assisted by the movement of migratory birds, the virus has spread near-worldwide with the exception of Australia and New Zealand, and has had unprecedented impacts on wild animal populations as well as devastating impacts on the poultry industry. **Understanding the potential role of wild birds in introducing and spreading HPAI virus in Australia is an important aspect of preparedness and response planning for human health and industry, as well as for wildlife managers**. Wildlife Health Australia has therefore compiled a [High Pathogenicity Avian Influenza (HPAI) clade 2.3.4.4b incursion risk assessment for Australia](https://wildlifehealthaustralia.com.au/Portals/0/ResourceCentre/BiosecurityMgmt/HPAI_incursion_risk_assessment_Australia.pdf). This document also includes information on the ecology and evolution of avian influenza and their avian hosts underpinning the risk assessment. Yet, the risk of a HPAI virus incursion to Australia, and of its subsequent establishment and spread, is fluid. The risk varies depending on where, when, and with what intensity HPAI virus is present in countries overseas and whether migratory birds can bring the virus from there to Australia. If an HPAI virus incursion into Australia occurs, establishment and further spread of the virus depends on where and when it arrives, and whether HPAI susceptible species are likely to present at that location in large numbers. To provide insights in these highly dynamic processes, we here bring together datasets on HPAI outbreaks, bird migrations, species at risk, and susceptible bird aggregations on our continent in a platform that will be updated whenever major developments in this space take place, so that stakeholders have all relevant information at hand in one place to be able to better evaluate the contemporary risk.

## HPAI outbreaks

We collated an interactive, zoomable map, at {HPAI outbreaks} showing locations of HPAI outbreaks using data from WAHIS (World Animal Health Information System) of the World Organisation for Animal Health (WOAH) (2022). The data presented includes both H5 and H7 HPAI outbreak events and need not necessarily represent outbreaks caused by HPAI H5N1 clade 2.3.4.4b virus (although since 2021, most of them are). We also provide an alternative map [here](https://vhost2009.hosted-sites.deakin.edu.au/HPAI/WOAH-MapOutbreaks.html), which allows to select a data range, identify confirmed H5 and H7 cases, and obtain more detailed information on each individual outbreak.

**It should be noted that WOAH bears no responsibility for the integrity or accuracy of the data contained herein, but not limited to, any deletion, manipulation, or reformatting of data that may have occurred beyond its control. For some events, incorrect data have recently been detected. WOAH is currently undertaking considerable efforts to solve these issues at the source and provide a dataset that is fully consistent with that reported by countries. WOAH will keep its users informed as the situation develops.**

In the interpretation of the data presented it should be borne in mind that countries may differ markedly in their level of screening and reporting of HPAI in poultry and wildlife.

## Bird migrations

Migratory birds might potentially introduce HPAI virus from overseas sites where HPAI occurs. The [High Pathogenicity Avian Influenza (HPAI) clade 2.3.4.4b incursion risk assessment for Australia](https://wildlifehealthaustralia.com.au/Portals/0/ResourceCentre/BiosecurityMgmt/HPAI_incursion_risk_assessment_Australia.pdf) identifies all migrants from the northern hemisphere migrating to Australia as potential vehicles of HPAI virus dispersal. However, based on (Australian, non-breeding) population sizes and their known susceptibility to avian influenza infection (Wille et al. 2023) [https://royalsocietypublishing.org/doi/10.1098/rspb.2022.2237] as well as their suitability in representing specific migration routes and strategies, we have limited ourselves to a few representative shorebird and seabird species. Under bird migrations {link to Bird migrations} we present an interactive map presenting the migratory routes and the timing of migrations for important shorebird and seabird species that migrate to and stay in Australia in the millions. 
The map depicts resighting data of colour marked shorebirds from http://www.birdmark.net collected by the Australasian Wader Studies Group, Global Flyway Network, Queensland Wader Study Group, and Victorian Wader Study Group. Also tracking data from mainly shorebirds and two very common shearwaters from a variety of published and unpublished sources (see table below) are presented in this map. Also depicted are distribution maps from Birds of the World (BirdLife International) for the various species for which banding and tracking data is presented. 

_TBA: Table of species for which migratory tracks are presented and their sources._

The phenology or timing of migrations is of particular relevance in this interactive map, highlighting that HPAI incursion risk is particularly high during the Austral Spring when migrants arrive from the northern hemisphere to Australia. With increasing presence of HPAI in Antarctica and Antarctic waters, the movements of the short-tailed shearwater (Australia’s most common migratory seabird, by far) are of particular interest as they too move into these regions. However, as the timing of their migrations indicates, they progressively move into these waters only after finishing breeding, when they no longer migrate back and forth between their pelagic feeding and Australian breeding grounds. These data thus suggest that the risk of a direct HPAI incursion from Antarctica into Australia on board this is small. 

## Species at Risk

According to the WAHIS information system from WOAH there have been 12151 outbreaks or notifications of HPAI in wild birds involving 129876 casualties, across 20 orders and 378 species of birds, since the start of the pandemic (1 October 2021).  In the below table and figure, an overview is generated of these bird species and how these are distributed across the different orders and families of birds. As outlined in [Klaassen and Wille 2023](https://doi.org/10.1038/s41559-023-02182-x), these data provide only an indication of the number of birds that have fallen victim to HPAI virus, the true numbers likely being much larger and in the millions.
In **Species at risk** we analysed these data to identify what Australian species are most of risk of infection with HPAI and therewith are most likely to fall victim to the virus, act as a reservoir for its maintenance and assist in the spread of the virus.
Increasingly, wild mammals are also affected by HPAI. According to the WAHIS information there have been 527 outbreaks or notifications of HPAI in wild mammals involving 6389 casualties, and 43 species of birds. In the below table and figure, an overview is generated of these species and how these are distributed across the different orders and families of mammals. As can be seen, the vast majority of them are carnivorous, with the route of infection probably by eating infected moribund or dead victims to HPAI virus.

## Bird Aggregations
After a possible incursion of HPAI virus, the risk of establishment and a further spread of HPAI is not only determined by the species at risk of infection with HPAI (tab **Species at Risk**) but importantly also where the large concentrations of these species reside in Australia (tab **Bird aggregations**)

_TBA: Chris to finalise_
